id: P010324
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:06.690197
source_metadata:
  id: bdr:W1KG14676
  title: དམིགས་པ་གེགས་སེལ་ཆེན་མོ།
  author: ''
  volumes:
    7567883d2add41fbb73ac9312e26b6ee:
      image_group_id: I1KG15764
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
