id: P010324
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14676
  title: དམིགས་པ་གེགས་སེལ་ཆེན་མོ།
  author: ''
  volumes:
    7567883d2add41fbb73ac9312e26b6ee:
      image_group_id: I1KG15764
      title: ''
      volume_number: 1
      total_pages: 132
